---
pipeline:
  build:
    test:
      deploy: "register_with_apphub"

steps:
  build:
    script: |
      service docker start && sleep 5 # Wait for docker daemon to start
      
      set -x
      docker pull predixadoption/devrelprediximage
      CONTAINER_ID=`docker run -d predixadoption/devrelprediximage tail -f /dev/null`
      #docker exec -t $CONTAINER_ID bash -c '
      #  cd /tmp && \
      #  git clone https://github.com/PredixCI/apphub-microapp-seed.git && \ 
      #  cd apphub-microapp-seed && \
      #  npm install && \
      #  npm run dist'
      docker commit $CONTAINER_ID apphub_microapp_seed
      docker save apphub_microapp_seed -o /root/apphub_microapp_seed.tar
    output: 
      - apphub_microapp_seed.tar
  test:
    input: 
      - apphub_microapp_seed.tar
    script: |
      service docker start && sleep 5
      
      docker load -i /root/apphub_microapp_seed.tar
      CONTAINER_ID=`docker run -d apphub_microapp_seed tail -f /dev/null`
      docker exec -it $CONTAINER_ID 'npm test'
  deploy:
    input: 
      - apphub_microapp_seed.tar
    script: "tar -xvf apphub-microapp-seed.tar && cd repos && cf push && cf apps"
  register_with_apphub:
    script: "scripts/apphub_registration.sh" #TODO
    environment:
      UAA_SERVICE_PLAN: 'Free'
      UAA_INSTANCE_NAME: 'predix_ci_apphub_uaa'
      PREDIX_APPHUB_NAME: 'predix_ci_apphub'
      PREDIX_APPHUB_PLAN: 'Beta'
      CLIENT_SECRET: '$CLIENT_SECRET'

