---
pipeline:
  build:
    test:
      deploy: "register_with_apphub"

steps:
  build:
    script: |
      service docker start && sleep 5 # Wait for docker daemon to start
      
      docker pull predixadoption/devrelprediximage
      CONTAINER_ID=docker run -d devrelprediximage tail -f /dev/null
      docker exec -it $CONTAINER_ID '
        git clone https://github.com/PredixCI/apphub-microapp-seed.git && \ 
        cd apphub-microapp-seed && \
        npm install && \
        npm run dist'
      docker commit $CONTAINER apphub_microapp_seed
      docker save apphub_microapp_seed -o apphub_microapp_seed.tar
    output: 
      - apphub_microapp_seed.tar
  test:
    input: 
      - apphub_microapp_seed.tar
    script: |
      service docker start && sleep 5
      
      docker load -i apphub_microapp_seed.tar
      CONTAINER_ID=docker run -d apphub_microapp_seed tail -f /dev/null
      docker exec -it $CONTAINER_ID 'npm test'
  deploy:
    input: 
      - apphub_microapp_seed.tar
    script: "tar -xvf apphub-microapp-seed.tar && cd repos && cf push && cf apps"
  register_with_apphub:
    script: "scripts/apphub_registration.sh"
    environment:
      UAA_SERVICE_PLAN: 'Free'
      UAA_INSTANCE_NAME: 'predix_ci_apphub_uaa'
      PREDIX_APPHUB_NAME: 'predix_ci_apphub'
      PREDIX_APPHUB_PLAN: 'Beta'
      CLIENT_SECRET: '$CLIENT_SECRET'

